config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins

  devise_for :workers, controllers: { registrations: "workers/registrations",
                                      sessions: 'workers/sessions' }

  namespace :admins do
    resources :manages, only: %i[ index ]
  end

  namespace :workers do
    resources :companies, only: %i[ show ]
    resources :accesses, only: %i[ show update ]
    resources :payment_methods, only: %i[ index new create edit update ]
    put 'company/alter-token', to: 'companies#reset_token'
  end

  resources :pix_methods, only: %i[ index show new create edit update ]
  resources :card_methods, only: %i[ index show new create edit update ]
  resources :billet_methods, only: %i[ index show new create edit update  ]

  resources :products, only: %i[ index new create show edit update]
  resources :discounts, only: %i[ new create show]

  namespace :api do
    namespace :v1 do
      resources :clients, only: %i[ index show create ]
      resources :billet_billings, only: %i[ create ]
      resources :card_billings, only: %i[ create ]
      resources :pix_billings, only: %i[ create ]
    end
  end
end

app/views/shared/_errors.html.erb
<% if object && object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <p>
      <%= message %>
    </p>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<h2 class = "home title_home" >
  <%= link_to "PayNow", root_path %>
</h2>

<div class = "header">

  <% if worker_signed_in? %>
    <p>
      <%= current_worker.email %> | 
      <%= link_to t('my_company'), workers_company_path(current_worker.company) %> | 

      <% if current_worker.admin?  %>
        <%= link_to t('manage_worker'), workers_access_path(current_worker) %> | 
      <% end %>

      <%= link_to t('logout'), destroy_worker_session_path, method: :delete %>
    </p>
  <% elsif admin_signed_in? %>
    <p style="color:#8A2BE2;">
      <%= current_admin.email %> | 
      <%= link_to 'Dashboard', admins_manages_path %> | 
      <%= link_to t('logout'), destroy_admin_session_path, method: :delete %>
    </p>
  <% else %>
      <p style="color:#8A2BE2;"> ➤ <%= link_to t('register'), new_worker_registration_path %>   | 
          ➤ <%= link_to t('login_account'), new_worker_session_path %></p>
  <% end %>
</div>

app/views/shared/_messages.html.erb
<div class="custom_notice">
  <% if notice %>
    <p class="custom_message_notice"><%= notice %></p>
  <% end %>
</div>

<div class="custom_alert">
  <% if alert %>
    <p class="custom_message_alert"><%= alert %></p>
  <% end %>
</div>