config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins

  devise_for :workers, controllers: { registrations: "workers/registrations",
                                      sessions: 'workers/sessions' }

  namespace :admins do
    resources :manages, only: %i[ index ]
  end

  namespace :workers do
    resources :companies, only: %i[ show ]
    resources :accesses, only: %i[ show update ]
    resources :payment_methods, only: %i[ index new create edit update ]
    put 'company/alter-token', to: 'companies#reset_token'
  end

  resources :pix_methods, only: %i[ index show new create edit update ]
  resources :card_methods, only: %i[ index show new create edit update ]
  resources :billet_methods, only: %i[ index show new create edit update  ]

  resources :products, only: %i[ index new create show edit update]
  resources :discounts, only: %i[ new create show]

  namespace :api do
    namespace :v1 do
      resources :clients, only: %i[ index show create ]
      resources :billet_billings, only: %i[ create ]
      resources :card_billings, only: %i[ create ]
      resources :pix_billings, only: %i[ create ]
    end
  end
end

app/models/card_method.rb
class CardMethod < ApplicationRecord
  belongs_to :company

  validates :name, presence: true
  validates :tax_charge, presence: true
  validates :tax_max, presence: true
  validates :code, presence: true
  validate :check_if_already_in_company

  def self.available_methods
    company = Company.find_by(corporate_name: 'Paynow')
    company.card_methods.where(available: true)
  end

  def self.clone_template(card_params, card_id)
    company = Company.find_by(corporate_name: 'Paynow')

    payment_method = company.card_methods.find(card_id).dup
    payment_method.update(card_params)
    payment_method
  end

  def check_if_already_in_company
    if self.company && self.company.card_methods.exists?(name: self.name) && self.id.nil? 
      errors.add(:base, :invalid, message: I18n.t('payment_method_already'))
    end
  end
end

app/controllers/card_methods_controller.rb
class CardMethodsController < ApplicationController
  before_action :authenticate_admin!
  before_action :paynow_company, only: %i[ index show new create edit update ]
  before_action :set_card_method, only: %i[ show edit update ]

  def index
    @card_methods = @paynow.card_methods.all
  end

  def new
    @card_method =  @paynow.card_methods.new
  end

  def create
    @card_method = @paynow.card_methods.new(card_method_params)
    msg = t('.success')
    return redirect_to @card_method, notice: msg if @card_method.save

    render :new
  end

  def show
  end

  def edit
  end

  def update
    msg = t('.success')
    return redirect_to @card_method, notice: msg if @card_method.update(card_method_params)

    render :new
  end

  private

  def card_method_params
    params.require(:card_method).permit(:name, :icon, :tax_charge, :tax_max, 
                                        :code, :available)
  end

  def paynow_company
    @paynow = Company.find_by(corporate_name: 'Paynow')
  end

  def set_card_method
    @card_method = @paynow.card_methods.find_by(id: params[:id])
  end
end

app/views/card_methods/_form.html.erb
<div class="container">
  <%= form_with model: card_method, local: true do |f| %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control" %>
    </p>

    <%= f.label :icon %>
      <%= f.text_field :icon, class:"form-control" %>
    </p>

    <p>
      <%= f.label :tax_charge %>
      <%= f.number_field :tax_charge, class:"form-control" %>
    </p>

    <p>
      <%= f.label :tax_max %>
      <%= f.number_field :tax_max, class:"form-control" %>
    </p>

    <p>
      <%= f.label :code %>
      <%= f.text_field :code, class:"form-control" %>
    </p>

    <p>
      <%= f.label :available %>
      <%= f.check_box :available %>
    </p>

    <p>
      <%= f.submit class:"btn btn-outline-primary"%>
    </p>
  <% end %>
</div>

app/views/card_methods/edit.html.erb
<div class="container">
  <p><%= link_to t('back'), card_methods_path, class:"btn btn-outline-primary" %></p>

  <h3><%= t('.edit_card') %></h3>

  <%= render 'shared/errors', object: @card_method %>

  <%= render 'form', card_method: @card_method %>
</div>

app/views/card_methods/index.html.erb
<div class="container">
  <p><%= link_to t('back'), admins_manages_path, class:"btn btn-outline-primary" %></p>
  <br>
  <h3><%= t('.card_method') %></h3>
  <br>
  <p><%= link_to t('.add'), new_card_method_path, class:"btn btn-outline-primary" %></p>

  <% @card_methods.each do |card_method| %>
    <p>
      <%= link_to card_method.name, card_method_path(card_method) %>
    </p>

    <p>
      <%= card_method.tax_charge %>
    </p>

    <p>
      <%= card_method.tax_max %>
    </p>

    <p>
      <%= card_method.code %>
    </p>

    <p>
      <%= card_method.available? ? t('.available') : t('.unavailable') %>
    </p>

    <p>
      <%= link_to  t('.edit'), edit_card_method_path(card_method), class:"btn btn-outline-primary" %>
    </p>
    <hr>
  <% end %>
</div>

app/views/card_methods/new.html.erb
<div class="container"> 
  <p><%= link_to t('back'), card_methods_path, class:"btn btn-outline-primary" %></p>

  <h3><%= t('.add_new_card') %></h3>

  <%= render 'shared/errors', object: @card_method %>

  <%= render 'form', card_method: @card_method %>
</div>

app/views/card_methods/show.html.erb
<div class="container">
  <p><%= link_to t('back'), card_methods_path, class:"btn btn-outline-primary" %></p>

  <h3><%= t('.details')%></h3>

  <p>
    <%= @card_method.name %>
  </p>

  <p>
    <%= @card_method.tax_charge %>
  </p>

  <p>
    <%= @card_method.tax_max %>
  </p>

  <p>
    <%= @card_method.code %>
  </p>

  <p>
    <%= @card_method.available? ? t('.available') : t('.unavailable') %>
  </p>
</div>