config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :admins

  devise_for :workers, controllers: { registrations: "workers/registrations",
                                      sessions: 'workers/sessions' }

  namespace :admins do
    resources :manages, only: %i[ index ]
  end

  namespace :workers do
    resources :companies, only: %i[ show ]
    resources :accesses, only: %i[ show update ]
    resources :payment_methods, only: %i[ index new create edit update ]
    put 'company/alter-token', to: 'companies#reset_token'
  end

  resources :pix_methods, only: %i[ index show new create edit update ]
  resources :card_methods, only: %i[ index show new create edit update ]
  resources :billet_methods, only: %i[ index show new create edit update  ]

  resources :products, only: %i[ index new create show edit update]
  resources :discounts, only: %i[ new create show]

  namespace :api do
    namespace :v1 do
      resources :clients, only: %i[ index show create ]
      resources :billet_billings, only: %i[ create ]
      resources :card_billings, only: %i[ create ]
      resources :pix_billings, only: %i[ create ]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  has_many :discounts

  validates :product_name, presence: true
  validates :product_price, presence: true

  def create_token
    input = self.product_name + Time.current.to_s + rand.to_s
    product_hash = Digest::SHA256.hexdigest(input)[0..19]
    self.token = product_hash
  end

  def self.is_existent?(token)
    !!Product.find_by(token: token)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_worker!

  def index
    @products = current_worker.company.products.all
  end

  def new
    @product = current_worker.company.products.new()
  end

  def create
    @product = current_worker.company.products.new(product_params)
    @product.create_token
    msg = t('.success')
    return redirect_to @product, notice: msg if @product.save

    render :new
  end

  def show
    @product = current_worker.company.products.find(params[:id])
  end

  def edit
    @product = current_worker.company.products.find(params[:id])
  end

  def update
    @product = current_worker.company.products.find(params[:id])
    msg = t('.success')
    return redirect_to @product, notice: msg if @product.update(product_params)

    render :edit
  end

  private

  def product_params
    params.require(:product).permit(:product_name, :product_price, :token)
  end

end

app/views/products/_form.html.erb
<div class="container">
  <%= form_with model: product, local: true do |f| %>
    <p>
      <%= f.label :product_name %>
      <%= f.text_field :product_name, class:"form-control" %>
    </p>

    <p>
      <%= f.label :product_price %>
      <%= f.number_field :product_price, step: 0.01, class:"form-control" %>
    </p>

    <p>
      <%= f.submit class:"btn btn-outline-primary" %>
    </p>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class = "container">

  <p><%= link_to t('back'), products_path, class:"btn btn-outline-primary" %></p>
  <h3><%= t('.edit_product') %></h3>

  <%= render 'shared/errors', object: @product %>
  <%= render 'form', product: @product %>

</div>

app/views/products/index.html.erb
 <div class="container"> 
  <h4><%= t('.products') %></h4>
  <br>
  <p>
    <%= link_to  t('.add_product'), new_product_path, class:"btn btn-outline-primary" %>
  </p>

  <div class="acesses_show">
    <% @products.each do |product| %>
      <p>
        <%= link_to product.product_name, product_path(product), class:"btn btn-outline-dark" %>
      </p>

      <p style="text-align:center">
        <%= link_to t('.edit_product'), edit_product_path(product), class:"btn btn-outline-dark" %>
      </p>
      <hr>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">

  <p><%= link_to t('back'), products_path, class:"btn btn-outline-primary"%></p>

  <h4><%= t('.add_product') %></h4>

  <%= render 'shared/errors', object: @product %>

  <%= render 'form', product: @product %>

</div>

app/views/products/show.html.erb
<div class="container">

  <h3><%= t('.product') %></h3>

  <h4>
    <%= @product.product_name %>
  </h4>

  <p>
    <%= t('.price') %>: 
    <%= number_to_currency(@product.product_price, unit: "R$", separator: ",", delimiter: ".", format: "%n %u")%>
  </p>

  <p>
    Token: <%= @product.token %>
  </p>

  <p>
    <%= link_to t('.add_discount'), new_discount_path({ id: @product.id }), class:"btn btn-outline-success" %>
  </p>

  <% if @product.discounts.any? %>
    <% @product.discounts.each do |discount| %>
      <p>
        <%= t('.payment_method') %>: <%= discount.payment_type %>
      </p>
      <p>
        <%= t('.discount') %>: <%= number_to_percentage(discount.amount, precision: 2) %>
      </p>
    <% end %>
  <% else %>
      <%= t('.no_discounts')%>
  <% end %>

  <p>
    <%= link_to t('back'), products_path, class:"btn btn-outline-primary" %>
  </p>
</div>